'use client';
import {useRef} from 'react';
import {useInView} from 'framer-motion';
import {Check,Palette,Layers,Sparkles} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
export const effectKinds=['aurora','dots','waves','stars','mesh','orbits','grid','beams','rain','ribbons','bubbles','sparks','facets','halo','flow'] as const;
export type EffectKind=typeof effectKinds[number];
export type BackgroundConfig={layers:EffectKind[];colors:string[];speed:number;intensity:number};
export type SectionEffects=Record<string,BackgroundConfig>;
const names=['Electric Aurora','Cosmic Dust','Tidal Light','Prism Field','Orbit Garden','Laser Horizon','Meteor Shower','Silk Motion','Bubble Universe','Spark Circuit','Crystal Drift','Solar Halo','Liquid Spectrum','Star Map','Neon Rain','Northern Bloom','Ocean Pulse','Stellar Veil','Digital Canopy','Moon Rings','Sunlit Beams','Firefly Drift','Velvet Ribbons','Floating Gems','Electric Ember','Glass Horizon','Lunar Tide','Plasma Stream','Constellation Grid','Violet Storm','Solar Threads','Deep Space','Ripple Network','Luminous Mesh','Saturn Glow','Golden Hour','Comet Trails','Color Cascade','Bubble Prism','Live Wire','Diamond Sky','Eclipse Aura','Molecular Flow','Galaxy Lines','Monsoon Lights'];
const palettes=[['#7185ff','#d067ee','#45d8dd'],['#73d5f8','#777cf4','#dba8fa'],['#29c9d3','#3c72f3','#92ebbb'],['#f48ed2','#8997ff','#f3c387'],['#b6e388','#72c7da','#8399ff'],['#e886ff','#5c99ff','#68ece0'],['#efbe69','#fb86b7','#8898ff'],['#97a5ff','#faacdd','#51d9d4'],['#8ee6d5','#ada0fd','#f1d186']];
export const backgroundPresets=names.map((name,i)=>({name,config:{layers:[effectKinds[i%15],effectKinds[(i%15+1+Math.floor(i/15)*4)%15]],colors:palettes[i%palettes.length],speed:[.8,1,1.3,1.5][i%4],intensity:[.5,.65,.8][Math.floor(i/15)]} as BackgroundConfig}));
export const defaultEffects:SectionEffects={global:{layers:['aurora','dots'],colors:palettes[0],speed:.8,intensity:.6},home:backgroundPresets[0].config,explore:backgroundPresets[12].config,about:backgroundPresets[4].config,classes:backgroundPresets[5].config,projects:backgroundPresets[8].config,learn:backgroundPresets[17].config,community:backgroundPresets[30].config,contact:backgroundPresets[27].config,footer:backgroundPresets[32].config};
function Effect({kind}:{kind:EffectKind}){return <div className={`effect-layer effect-${kind}`}>{Array.from({length:['dots','stars','rain','sparks','bubbles'].includes(kind)?18:6},(_,i)=><i key={i} style={{'--n':i,'--x':`${(i*37+13)%100}%`,'--y':`${(i*23+11)%100}%`,'--delay':`${i*-.71}s`} as React.CSSProperties}/>)}</div>}
export function AnimatedBackdrop({config,fixed=false,mini=false}:{config:BackgroundConfig;fixed?:boolean;mini?:boolean}){const ref=useRef<HTMLDivElement>(null);const visible=useInView(ref,{margin:'100px'});return <div ref={ref} aria-hidden="true" className={`animated-backdrop ${fixed?'backdrop-fixed':''} ${mini?'backdrop-mini':''} ${visible||fixed?'backdrop-running':'backdrop-paused'}`} style={{'--fx-a':config.colors[0],'--fx-b':config.colors[1]||config.colors[0],'--fx-c':config.colors[2]||config.colors[1],'--fx-speed':config.speed,'--fx-intensity':config.intensity} as React.CSSProperties}>{config.layers.slice(0,2).map(kind=><Effect key={kind} kind={kind}/>)}</div>}
export function ThemeStudio({effects,setEffects,section,setSection}:{effects:SectionEffects;setEffects:React.Dispatch<React.SetStateAction<SectionEffects>>;section:string;setSection:(v:string)=>void}){const config=effects[section]||defaultEffects[section]||defaultEffects.global;const set=(change:Partial<BackgroundConfig>)=>setEffects(old=>({...old,[section]:{...config,...change}}));return <div className="studio-fields"><h3><Palette size={19}/> Background laboratory</h3><p className="studio-help">45 distinct combinations. Mix up to two animations, then tune color, speed and intensity.</p><div className="theme-sections">{Object.keys(defaultEffects).map(s=><button key={s} className={section===s?'active':''} onClick={()=>setSection(s)}>{s}</button>)}</div><div className="mixer-preview"><AnimatedBackdrop config={config} mini/><span><Layers size={18}/>{config.layers.join(' + ')}</span></div><div className="effect-mixer"><h4>Animation mixer <small>{config.layers.length} / 2</small></h4><div>{effectKinds.map(kind=><button key={kind} aria-pressed={config.layers.includes(kind)} className={config.layers.includes(kind)?'active':''} onClick={()=>{if(config.layers.includes(kind)){if(config.layers.length>1)set({layers:config.layers.filter(x=>x!==kind)})}else set({layers:config.layers.length===2?[config.layers[0],kind]:[...config.layers,kind]})}}><Sparkles size={13}/>{kind}{config.layers.includes(kind)&&<Check size={13}/>}</button>)}</div></div><div className="mixer-color-row">{config.colors.map((color,i)=><label key={i}>Color {i+1}<input type="color" value={color} onChange={e=>set({colors:config.colors.map((c,j)=>j===i?e.target.value:c)})}/></label>)}</div><label className="form-label">Motion speed • {config.speed.toFixed(1)}×<Slider aria-label="Animation speed" min={.3} max={2.5} step={.1} value={[config.speed]} onValueChange={([speed])=>set({speed})}/></label><label className="form-label">Color intensity • {Math.round(config.intensity*100)}%<Slider aria-label="Background intensity" min={.15} max={1} step={.05} value={[config.intensity]} onValueChange={([intensity])=>set({intensity})}/></label><h4>Preset library</h4><div className="distinct-preset-grid">{backgroundPresets.map(p=><button key={p.name} onClick={()=>setEffects(old=>({...old,[section]:{...p.config,colors:[...p.config.colors],layers:[...p.config.layers]}}))}><AnimatedBackdrop config={p.config} mini/><span>{p.name}<small>{p.config.layers.join(' + ')}</small></span></button>)}</div></div>}
