'use client';
import {useState} from 'react';
import {motion,AnimatePresence,useReducedMotion} from 'framer-motion';
import {Lightbulb,Check,Sparkles,MessageCircle,Atom,ChevronRight,Share2,FlaskConical,BookOpen,GraduationCap,ExternalLink} from 'lucide-react';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogAction,AlertDialogCancel,AlertDialogFooter} from '@/components/ui/alert-dialog';
import {mediaDisplayUrl} from './media-display';
import type {Album} from './MediaCollections';
import type {VideoLesson} from './VideoLibrary';
export type Appearance={layout:'enhanced'|'original';footer:'mosaic'|'classic';notesEnabled?:boolean;performanceMode?:'standard'|'minimal'};
export const defaultAppearance:Appearance={layout:'enhanced',footer:'mosaic',notesEnabled:false,performanceMode:'standard'};
const questions=[{question:'වතුරට දැමූ පැන්සලක් නැමී පෙනෙන්නේ ඇයි?',choices:['ආලෝකයේ වර්තනය නිසා','ගුරුත්වාකර්ෂණය නිසා','පැන්සල ඇත්තටම නැමෙන නිසා'],correct:0,answer:'ආලෝකය ජලයෙන් වාතයට යන විට එහි දිශාව වෙනස් වෙනවා. මේ වර්තනය නිසා ජලය තුළ ඇති පැන්සලේ කොටස වෙනත් තැනක තියෙනවා වගේ පෙනෙනවා.'},{question:'දිවා කාලයේ අහස නිල් පැහැයෙන් පෙනෙන්නේ ඇයි?',choices:['මුහුදේ පැහැය පරාවර්තනය වන නිසා','කෙටි තරංග ආයාම සහිත ආලෝකය වැඩියෙන් විසිරෙන නිසා','වාතය නිල් පාට නිසා'],correct:1,answer:'සූර්යාලෝකය වායුගෝලය හරහා යන විට කෙටි තරංග ආයාම සහිත ආලෝකය වැඩියෙන් විසිරෙනවා. මේ නිසා අපට අහස බොහෝ විට නිල් පැහැයෙන් පෙනෙනවා.'},{question:'ශාක ප්‍රභාසංශ්ලේෂණයේදී භාවිත කරන වායුව කුමක්ද?',choices:['ඔක්සිජන්','නයිට්‍රජන්','කාබන් ඩයොක්සයිඩ්'],correct:2,answer:'හරිත ශාක ආලෝක ශක්තිය, ජලය සහ කාබන් ඩයොක්සයිඩ් භාවිතයෙන් ආහාර නිපදවයි. මේ ක්‍රියාවලියේදී ඔක්සිජන් නිකුත් වේ.'}];
export function DiscoveryLab(){const [index,setIndex]=useState(0),[answer,setAnswer]=useState<number|null>(null);const q=questions[index];const reduced=useReducedMotion();return <div className="meaningful-discovery"><div className="discovery-intro"><span className="label-chip"><Lightbulb size={17}/> A MINUTE OF WONDER</span><h2>අද අලුත් දෙයක්<br/><span className="serif-accent">සොයාගමු ද?</span></h2><p>පොතේ සංකල්ප ඔබ වටා තියෙනවා.<br/>පුංචි ප්‍රශ්නයකින් පටන් ගමු.</p><div className="learning-route">{[{icon:Lightbulb,title:'ප්‍රශ්නයක් අහන්න'},{icon:FlaskConical,title:'නිරීක්ෂණය කරන්න'},{icon:BookOpen,title:'හේතුව තේරුම් ගන්න'},{icon:GraduationCap,title:'දැනුම භාවිත කරන්න'}].map((s,i)=><div key={s.title}><span><s.icon size={19}/></span><small>0{i+1}</small><b>{s.title}</b></div>)}</div></div><div className="daily-question"><div className="question-label"><Sparkles size={17}/><span>SCIENCE IN YOUR EVERYDAY</span><small>0{index+1} / 03</small></div><AnimatePresence mode="wait"><motion.div key={index} initial={reduced?false:{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-15}}><h3>{q.question}</h3><div className="question-choices">{q.choices.map((c,i)=><button key={c} aria-pressed={answer===i} className={answer!==null&&i===q.correct?'correct':answer===i?'incorrect':''} onClick={()=>setAnswer(i)}><span>{String.fromCharCode(65+i)}</span>{c}{answer!==null&&i===q.correct&&<Check size={18}/>}</button>)}</div>{answer!==null&&<motion.div className="question-explanation" initial={reduced?false:{opacity:0,y:8}} animate={{opacity:1,y:0}}><b>{answer===q.correct?'හරියටම හරි!':'අපි හේතුව බලමු.'}</b><p>{q.answer}</p></motion.div>}</motion.div></AnimatePresence><button className="next-question" onClick={()=>{setIndex((index+1)%questions.length);setAnswer(null)}}>තවත් ප්‍රශ්නයක් <ChevronRight size={17}/></button></div></div>}
export function SignatureFooter({albums,videos,portrait,name,logo,brand,credit,tag,socials,onInquiry,onShare,onAdmin}:{albums:Album[];videos:VideoLesson[];portrait:string;name:string;logo:string;brand:string;credit:string;tag:string;socials:Record<string,string>;onInquiry:()=>void;onShare:()=>void;onAdmin:()=>void}){const photos=[...new Map([...albums.filter(a=>a.id!=='timetable').flatMap(a=>a.items.filter(m=>m.type==='image'&&m.id!=='lab').map(m=>({url:m.url,caption:m.caption}))),...(portrait?[{url:portrait,caption:name}]:[]),...videos.filter(v=>v.thumbnail).map(v=>({url:v.thumbnail,caption:v.title}))].map(p=>[p.url,p])).values()];const padded=(items:typeof photos)=>{const filled=items.length?[...items]:photos.length?[photos[0]]:[];if(filled.length%2)filled.push(filled[0]);return filled};const left=padded(photos.filter((_,i)=>i%2===0)),right=padded(photos.filter((_,i)=>i%2!==0));function wall(items:typeof photos,side:string){return <div className={`signature-wall wall-${side}`}><div className="signature-wall-track">{[0,1].map(group=><div className="signature-wall-group" key={group} aria-hidden={group===1}>{items.map((p,i)=><a tabIndex={group===1?-1:0} key={`${p.url}-${i}`} href={p.url} target="_blank" rel="noreferrer" className={`signature-photo photo-${i%4}`}><img src={mediaDisplayUrl(p.url)} data-original={p.url} alt={p.caption} loading="lazy"/></a>)}</div>)}</div></div>}return <div className="signature-composition">{left.length?wall(left,'left'):<div className="signature-wall signature-placeholder"><Atom size={55}/><FlaskConical size={40}/></div>}<div className="signature-center"><span className="signature-eyebrow">{logo?<img src={logo} alt={`${brand} logo`}/>:<Sparkles size={15}/>} {brand}</span><h2><span>Science <i>with</i></span><strong>{name}</strong></h2><p>කුතුහලයෙන් පටන්ගෙන,<br/>දැනුමෙන් ලෝකය දකිමු.</p><button className="btn acid" onClick={onInquiry}><MessageCircle size={18}/> අපි පටන් ගමු</button><button className="signature-share" onClick={onShare}><Share2 size={15}/> Share profile</button><div className="signature-socials">{Object.entries(socials).filter(([,url])=>url).map(([label,url])=><a href={url} key={label} target="_blank" rel="noreferrer">{label}<ExternalLink size={12}/></a>)}</div></div>{right.length?wall(right,'right'):<div className="signature-wall signature-placeholder"><GraduationCap size={55}/><BookOpen size={40}/></div>}<div className="signature-baseline"><span>© {new Date().getFullYear()} {brand}</span><button onClick={onAdmin}>Created by {credit}</button><span>{tag}</span></div></div>}
export function RestorePanel({appearance,setAppearance,onRestore,preview}:{appearance:Appearance;setAppearance:React.Dispatch<React.SetStateAction<Appearance>>;onRestore:(key:string)=>Promise<void>;preview:boolean}) {
  const [key,setKey]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
  const performanceMode=appearance.performanceMode||'standard';
  return <div className="studio-fields">
    <h3>Performance mode</h3>
    <p className="studio-help">Choose how much motion the website uses. Basic mode removes the 3D hero, animated backgrounds and interface motion for lower-powered classroom displays. The footer animation remains.</p>
    <div className="design-switch" role="group" aria-label="Website performance mode">
      {(['standard','minimal'] as const).map(mode=><button key={mode} type="button" aria-pressed={performanceMode===mode} className={performanceMode===mode?'active':''} onClick={()=>setAppearance(a=>({...a,performanceMode:mode}))}>{mode==='standard'?'Ultra · full effects':'Basic · e-board'}{performanceMode===mode&&<Check size={16}/>}</button>)}
    </div>
    <h3>Design & restore</h3><p className="studio-help">Switch back to the previous design while keeping your uploads and content.</p>
    <div className="design-switch">{(['enhanced','original'] as const).map(layout=><button key={layout} className={appearance.layout===layout?'active':''} onClick={()=>setAppearance(a=>({...a,layout,footer:layout==='original'?'classic':'mosaic'}))}>{layout==='enhanced'?'New design':'Original design'}{appearance.layout===layout&&<Check size={16}/>}</button>)}</div>
    <h4>Footer style</h4><div className="design-switch">{(['mosaic','classic'] as const).map(footer=><button key={footer} className={appearance.footer===footer?'active':''} onClick={()=>setAppearance(a=>({...a,footer}))}>{footer==='mosaic'?'Photo signature':'Classic footer'}</button>)}</div>
    <div className="restore-checkpoint"><h4>Saved checkpoints</h4><p>Restore the content saved before this redesign, or the last saved content. Uploaded files stay in storage.</p>{preview?<p>Content checkpoints are available on the live website.</p>:<>{[['before-polish','Before this redesign'],['previous','Previous saved content']].map(([k,label])=><button key={k} disabled={busy} onClick={()=>setKey(k)}>{label}</button>)}</>}<p role="status">{status}</p></div>
    <AlertDialog open={!!key} onOpenChange={v=>!v&&setKey('')}><AlertDialogContent className="standard-dialog"><AlertDialogTitle>Restore saved content?</AlertDialogTitle><AlertDialogDescription>This replaces the current text, media collections, timetable and design settings with the selected checkpoint. The current saved content will become the previous checkpoint.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={async()=>{setBusy(true);try{await onRestore(key);setStatus('Checkpoint restored. Saving your changes…')}catch(e){setStatus(e instanceof Error?e.message:'Restore failed')}finally{setBusy(false);setKey('')}}}>Restore checkpoint</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>
}
